version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - '${SERVER_PORT:-8080}:${SERVER_PORT:-8080}'
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgres://user:password@db:5432/todo_db?sslmode=disable}
      - SERVER_ADDRESS=:${SERVER_PORT:-8080}
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret}
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - SENTRY_DSN=${SENTRY_DSN:-}
      - AUTH_PRIVATE_KEY=${AUTH_PRIVATE_KEY}
      - AUTH_SALT=${AUTH_SALT}
    volumes:
      - ../:/app
      - auth_keys:/app/auth_keys
    command: air -c .air.toml
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=${DB_USER:-user}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-password}
      - POSTGRES_DB=${DB_NAME:-todo_db}
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  auth_keys:
