name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
      - name: Install Swag
        run: go install github.com/swaggo/swag/cmd/swag@latest
      - name: Add Swag to PATH
        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Generate Swagger Docs
        run: make swag
      - name: Build
        run: make build
      - name: Test
        run: make test
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
